const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const UPDATE_INFO = 'UPDATE_INFO';
const SEND_MESSAGE = 'SEND_MESSAGE';
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
const USER_DISCONNECT = 'USER_DISCONNECT';
const USER_JOIN = 'USER_JOIN';
const USER_TYPING = 'USER_TYPING';
const UPDATE_ROOMS = 'UPDATE_ROOMS';

module.exports = {
	CREATE_ROOM,
	JOIN_ROOM,
	UPDATE_INFO,
	SEND_MESSAGE,
	RECEIVE_MESSAGE,
	USER_DISCONNECT,
	USER_JOIN,
	USER_TYPING,
	UPDATE_ROOMS
}
